version: "3.9"

services:
  local:
    build: ./
    stdin_open: true
    tty: true
    image: speech-stats:v0.0.1
    volumes:
      - ./:/workspace
      - /mnt/d/datasets/:/datasets
    ulimits:
      memlock: -1
      stack: 67108864
    shm_size: 32gb